  # prettier-ignore
  name: Release and deploy
  on:
    pull_request:
      branches:
        - main
  jobs:
    release:
    - uses: ./.github/workflows/release.yml

    deploy:
    - uses: ./.github/workflows/deploy.yml
      needs: [release]
