name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate storybook files
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run deploy-storybook

      - name: Publish github page
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          folder: ./packages/ui/react/storybook-static
          target_folder: docs
