# prettier-ignore
name: Deploy to GitHub pages
on: 
  workflow_call:
    jobs:
      install:
        runs-on: ubuntu-latest
        steps:
        - name: Install dependencies
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '18.16.0'
            registry-url: https://registry.npmjs.org/
        - run: npm ci
        - run: npm run bootstrap

        - name: Build
        - run: npm run build

        - name: Release
        - run: npm run release
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
